"""Add StandardBreachName model and standard_breach_id to Breach

Revision ID: 222dda219cde
Revises: 
Create Date: 2025-02-02 12:18:55.231287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222dda219cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_breach_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_breach_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'standard_breach_names', ['standard_breach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('standard_breach_id')

    op.drop_table('standard_breach_names')
    # ### end Alembic commands ###
